/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package start;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import function.fileData;
import history.history;
import javax.swing.ImageIcon;
import user.userProfile;

/**
 *
 * @author NGUYEN VAN KIEN
 */
public class startTest extends javax.swing.JFrame {

    public void handl() throws IOException{
        ImageIcon icon;
        icon = new ImageIcon("src/data/img_avatar/avatar"+ String.valueOf(fileData.readAvatar()) +".png");
        avatar.setIcon(icon);
        String s ="";
        s =fileData.checkUserLogin();
        if(s!=null){
            if(s.length() >=3)
                avatar.setText(s);
        }
    }
    public startTest() throws IOException {
        initComponents();
        setLocationRelativeTo(null);
        handl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        avatar = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        user = new javax.swing.JButton();
        history = new javax.swing.JButton();
        startN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        line1 = new javax.swing.JLabel();
        line2 = new javax.swing.JLabel();
        line33 = new javax.swing.JLabel();
        line4 = new javax.swing.JLabel();
        line5 = new javax.swing.JLabel();
        line6 = new javax.swing.JLabel();
        line71 = new javax.swing.JLabel();
        line72 = new javax.swing.JLabel();
        line73 = new javax.swing.JLabel();
        slider = new javax.swing.JSlider();
        line8 = new javax.swing.JLabel();
        line9 = new javax.swing.JLabel();
        line10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm thi thử lý thuyết bằng lái xe hạng A1");

        avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/img_avatar/avatar1.png"))); // NOI18N
        avatar.setText("no_name");
        avatar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        avatar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        start.setBackground(new java.awt.Color(153, 153, 255));
        start.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        start.setText("Bắt đầu");

        user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user.setText("Người dùng");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        history.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        history.setText("Lịch sử");
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(history, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        startN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        startN.setText("Bắt đầu thi");
        startN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startNActionPerformed(evt);
            }
        });

        line1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        line1.setText(" - Đây là hệ thống thi thử bằng lái xe hạng A1.");

        line2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        line2.setText(" - Đề thi gồm 25 câu hỏi bao gồm :");

        line33.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        line33.setText("    + 15 câu lý thuyết ");

        line4.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        line4.setText("    + 5 câu biển báo ");

        line5.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        line5.setText("    + 5 câu sa hình ");

        line6.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        line6.setText(" - Nhấn bắt đầu thi để bắt đầu làm bài.");

        line71.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        line71.setText(" - Thời gian làm bài là");

        line72.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        line72.setText("19");

        line73.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        line73.setText("phút(tối đa 19 phút).");

        slider.setBackground(new java.awt.Color(255, 255, 255));
        slider.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        slider.setMajorTickSpacing(2);
        slider.setMaximum(19);
        slider.setMinimum(1);
        slider.setMinorTickSpacing(1);
        slider.setPaintLabels(true);
        slider.setPaintTicks(true);
        slider.setToolTipText("");
        slider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sliderMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sliderMouseReleased(evt);
            }
        });

        line8.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        line8.setText(" - Bạn vẫn có thể nộp bài sau khi đã hết thời gian , tuy nhiên");

        line9.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        line9.setText(" kết quả bài thi sẽ không được lưu lại.");

        line10.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        line10.setText("- Chúc bạn hoàn thành bài thi thật tốt!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(line71)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(line72)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(line73))
                            .addComponent(line6, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line5, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line4, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line33, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line8, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line9, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line10, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(line1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(line2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(line33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(line4)
                .addGap(10, 10, 10)
                .addComponent(line5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(line6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(line71)
                    .addComponent(line72)
                    .addComponent(line73))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(line8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(line9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(line10)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(543, 543, 543)
                        .addComponent(startN, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(startN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        try {
                new userProfile().setVisible(true);
                this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(startTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_userActionPerformed

    private void startNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startNActionPerformed
        try {
            String x1 = String.valueOf(slider.getValue());
            fileData.addSetTime(x1);
            
        } catch (IOException ex) {
            Logger.getLogger(startTest.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        new startExam().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_startNActionPerformed

    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
        new history().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_historyActionPerformed

    private void sliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderMouseClicked
        String x1 = String.valueOf(slider.getValue());
        if(x1.length()==1)
            x1 = "0" +x1;
        line72.setText(x1);
    }//GEN-LAST:event_sliderMouseClicked

    private void sliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderMouseReleased
        String x1 = String.valueOf(slider.getValue());
        if(x1.length()==1)
            x1 = "0" +x1;
        line72.setText(x1);
    }//GEN-LAST:event_sliderMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new startTest().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(startTest.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatar;
    private javax.swing.JButton history;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel line1;
    private javax.swing.JLabel line10;
    private javax.swing.JLabel line2;
    private javax.swing.JLabel line33;
    private javax.swing.JLabel line4;
    private javax.swing.JLabel line5;
    private javax.swing.JLabel line6;
    private javax.swing.JLabel line71;
    private javax.swing.JLabel line72;
    private javax.swing.JLabel line73;
    private javax.swing.JLabel line8;
    private javax.swing.JLabel line9;
    private javax.swing.JSlider slider;
    private javax.swing.JButton start;
    private javax.swing.JButton startN;
    private javax.swing.JButton user;
    // End of variables declaration//GEN-END:variables
}
