/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package start;

import javax.swing.ImageIcon;

/**
 *
 * @author NGUYEN VAN KIEN
 */
public class startExam2 extends javax.swing.JFrame {

    /**
     * Creates new form startExam2
     */
    public startExam2() {
        initComponents();
    //    ImageIcon s1 = createImageIcon("101.png");
    //    imgQs7.setIcon(s1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        panelImg = new javax.swing.JPanel();
        imgQs6 = new javax.swing.JLabel();
        qs6 = new javax.swing.JLabel();
        option6A = new javax.swing.JRadioButton();
        option6C = new javax.swing.JRadioButton();
        option6B = new javax.swing.JRadioButton();
        option6D = new javax.swing.JRadioButton();
        qs7 = new javax.swing.JLabel();
        option7A = new javax.swing.JRadioButton();
        option7B = new javax.swing.JRadioButton();
        option7D = new javax.swing.JRadioButton();
        option7C = new javax.swing.JRadioButton();
        img6 = new javax.swing.JLabel();
        img7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm thi thử lý thuyết bằng lái xe hạng A1");

        imgQs6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        qs6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qs6.setText("jLabel3");

        buttonGroup7.add(option6A);
        option6A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        buttonGroup7.add(option6C);
        option6C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        buttonGroup7.add(option6B);
        option6B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        buttonGroup7.add(option6D);
        option6D.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        qs7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qs7.setText("jLabel4");

        buttonGroup8.add(option7A);
        option7A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        buttonGroup8.add(option7B);
        option7B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        buttonGroup8.add(option7D);
        option7D.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        buttonGroup8.add(option7C);
        option7C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        img6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/img_notice/168.png"))); // NOI18N

        img7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/img_notice/168.png"))); // NOI18N

        javax.swing.GroupLayout panelImgLayout = new javax.swing.GroupLayout(panelImg);
        panelImg.setLayout(panelImgLayout);
        panelImgLayout.setHorizontalGroup(
            panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImgLayout.createSequentialGroup()
                .addGroup(panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(qs6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImgLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelImgLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(option7B)
                                    .addComponent(option7A)
                                    .addComponent(option7C)
                                    .addComponent(option7D))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(img7, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelImgLayout.createSequentialGroup()
                                .addGroup(panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(option6D)
                                    .addComponent(option6C)
                                    .addComponent(option6A)
                                    .addComponent(option6B))
                                .addGroup(panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelImgLayout.createSequentialGroup()
                                        .addGap(216, 216, 216)
                                        .addComponent(imgQs6, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                        .addGap(557, 557, 557))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImgLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(img6, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(2, 2, 2))
            .addGroup(panelImgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(qs7, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelImgLayout.setVerticalGroup(
            panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImgLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(qs6)
                .addGroup(panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(img6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImgLayout.createSequentialGroup()
                        .addGroup(panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelImgLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imgQs6))
                            .addGroup(panelImgLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(option6A)
                                .addGap(34, 34, 34)
                                .addComponent(option6B)
                                .addGap(33, 33, 33)
                                .addComponent(option6C)
                                .addGap(34, 34, 34)
                                .addComponent(option6D)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qs7)
                .addGroup(panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImgLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(option7A)
                        .addGap(32, 32, 32)
                        .addComponent(option7B)
                        .addGap(33, 33, 33)
                        .addComponent(option7C)
                        .addGap(35, 35, 35)
                        .addComponent(option7D))
                    .addGroup(panelImgLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(img7, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(panelImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startExam2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startExam2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startExam2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startExam2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
       //     @Override
            public void run() {
                new startExam2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JLabel img6;
    private javax.swing.JLabel img7;
    private javax.swing.JLabel imgQs6;
    private javax.swing.JRadioButton option6A;
    private javax.swing.JRadioButton option6B;
    private javax.swing.JRadioButton option6C;
    private javax.swing.JRadioButton option6D;
    private javax.swing.JRadioButton option7A;
    private javax.swing.JRadioButton option7B;
    private javax.swing.JRadioButton option7C;
    private javax.swing.JRadioButton option7D;
    private javax.swing.JPanel panelImg;
    private javax.swing.JLabel qs6;
    private javax.swing.JLabel qs7;
    // End of variables declaration//GEN-END:variables

}
